Layover_Connections/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('layoverconnections.urls', namespace='layoverconnections')),
    path('events/', include('events.urls', namespace='events')),
    path('admin/', admin.site.urls),
]

Layover_Project/Layover_Connections_app/urls.py
# django_project/urls.py 
from django.contrib import admin
from django.urls import path, include # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signon/', include('django.contrib.auth.urls')), # new
]

events/urls.py
from django.urls import path
from django.contrib import admin
from . import views

# Pre-Deployment Media Storage recommendations
from django.conf import settings
from django.conf.urls.static import static

# Event paths: events/<view_of_interest>
app_name = "events"
urlpatterns = [
    path("", views.view_events, name="view_events"),
    path("create_event", views.create_event, name="create_event"),
    path("end_product", views.end_product, name="formatted_event"),
    path("<int:event_id>/event_details/", views.event_details, name="event_details"),
    path("<int:event_id>/edit_event/", views.edit_event, name="edit_event"),
    path("<int:event_id>/delete_event/", views.delete_event, name="delete_event"),
] 

# Pre-Deployment check to see if currently in DEBUG mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

layoverconnections/urls.py
from django.urls import path
from django.contrib import admin
from layoverconnections import views
from . import views

# Pre-Deployment Media Storage recommendations
from django.conf import settings
from django.conf.urls.static import static

app_name = "layoverconnections"

# Homepage is django placeholder consider removing it
urlpatterns = [
    path("", views.index, name="index"),
    path("main", views.homepage, name="homepage"),
    path("register", views.register_request, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("user_profile", views.user_profile, name="profile"),
    path("<int:user_profile_id>/edit_profile", views.edit_profile, name="editprofile"),
    path("<int:user_id>/user_profile/", views.public_profile, name="public_profile"),
    path("delete_profile", views.delete_profile, name="delete_profile"),
    path("about_me", views.edit_bio, name="aboutme"),
    path("events", views.create_event, name="events"),
] 

# Pre-Deployment check to see if currently in DEBUG mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image


# Prototype model for Events
class Event(models.Model):
    description = models.CharField(max_length=250, blank=True)
    title = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    participants = models.ManyToManyField(User)
    # Add a field to store the host's user id.
    host = models.IntegerField(null=True)
    # Add Event Thumbnail and provide a default.
    event_thumbnail = models.ImageField(default='event_placeholder.jpg', upload_to='event_thumbnails')

    # Host permissions created via model attributes.
    class Meta:
        permissions = (('can_edit_event', 'Host Controls'),)

    def __str__(self):
        return f"Title: {self.title} \n"
    
    # Allows for get object or 404 & to insert args into URL route reqs: (/host/title)
    def get_absolute_url(self):
        return reverse('events:event_details', kwargs={"event_id": self.pk})
    
    # Provide Manager for saving event thumbnail (Maybe unneccesary/redundant)
    def save(self, *args, **kwargs):
        super(Event, self).save(*args, **kwargs)

        img = Image.open(self.event_thumbnail.path)

        # Provide size restrictions of user uploaded images (300x300)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.event_thumbnail.path)

events/forms.py
from django import forms
from .models import Event

# Event model forms
# Formatting for event creation.
class EventCreationForm(forms.ModelForm):
	title = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 1}))
	start_time = forms.CharField(label= 'Start Time: [ yyyy-mm-dd 00:00 ]')
	description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
	# TODO Fix the default event_thumbnail error.
	#event_thumbnail = forms.ImageField(required=False)
	event_thumbnail = forms.ImageField()

	class Meta:
		model = Event
		fields = ['title', 'event_thumbnail', 'start_time', 'end_time', 'description']


# [Placeholder form] in case I make the update form different.
class EventUpdateForm(forms.ModelForm):
	title = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 1}))
	start_time = forms.CharField(label= 'Start Time: [ yyyy-mm-dd 00:00 ]')
	description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
	event_thumbnail = forms.ImageField()

	class Meta:
		model = Event
		fields = ['title', 'event_thumbnail', 'start_time', 'end_time', 'description']

events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Permission
from events.models import Event, User
from django.contrib import messages
from .forms import EventCreationForm


# Base Event Page to encapsulate all event controls.
def event_base(request):
	return render(request, 'events/event_splashpage.html')

# Base Event Page to encapsulate all event controls.
def view_events(request):
	event_list = Event.objects.all()

	context = {
		"Events": event_list,
	}

	return render(request, 'events/existing_event.html', context)

# Load form variables for the event creation portal.
@login_required 
def create_event(request):
	if request.method == 'POST':
		Event_Form = EventCreationForm(request.POST, request.FILES)
		# Store host & title, apply host controls to the current user.
		host = request.user

		if Event_Form.is_valid():
			event_title = Event_Form.cleaned_data['title']
			Event_Form.save()
			# Retrieve event and add current user as participant, store user to make them a host with permissions in edit_details().
			New_Event = Event.objects.get(title=event_title)
			New_Event.host = (host.id)
			New_Event.participants.add(host)
			# Provide Host with elevated event permissions to allow them to modify/delete the event.
			edit_permission = Permission.objects.get(codename='can_edit_event')
			print(f"This is the permission object queried {edit_permission}")
			host.user_permissions.add(edit_permission)

			New_Event.save()

			messages.success(request, f"Event has been created")
			return redirect(reverse("events:view_events"))
	else:
		Event_Form = EventCreationForm()

	context = {
		'Event_Form': Event_Form
	}

	return render(request, 'events/create_event.html', context)


# Render single event details Allow the host to edit and for guest to join.
def event_details(request, event_id):
	event_details = get_object_or_404(Event, pk = event_id)
	# Query Host Participant details to link profile and thumbnail.
	host_id = event_details.host
	host = User.objects.get(id=host_id)

	# Allow user to join event.
	if request.method == "POST":
		event_details.participants.add(request.user)
		event_details.save()
		messages.success(request, f"You have joined the event.")
		return render(request, 'events/event_details.html', {"event_details": event_details})

	context = {
		"event_details": event_details,
		"host": host,
	}

	return render(request, 'events/event_details.html', context)


# Allow Host User to modify the event. Raise HTTP 403 Error code if the user is unauthorized.
@permission_required('events.can_edit_event', raise_exception=True)
def edit_event(request, event_id):
	# Load event model details to prepopulate the form fields.
	event_details = get_object_or_404(Event, pk = event_id)
	update_form = EventCreationForm(instance=event_details)

	# Store user id to validate against event host id
	current_user = request.user
	host = current_user.id
	event_host = event_details.host

	# Only allow user to modify event details if they're a host.
	if host == event_host:
		if request.method == "POST":
			update_form = EventCreationForm(request.POST,
								   		 	request.FILES,
											instance=event_details)
			if update_form.is_valid():
				update_form.save()
				# FIXME Django routing messages to admin/ login portal url insert messages with JavaScript
				messages.success(request, f"Your Event {format(update_form)} has been updated.")
				return render(request, 'events/event_details.html', {"event_details": event_details,})
		# TODO : Add JS popup denoting that changes are invalid.
		else:
			update_form = EventCreationForm(instance=event_details)
	# Route user to event details if they aren't the host.
	# TODO Add JavaScript popup message saying user is unauthorized to edit event information
	else:
		context = {"event_details": event_details,}
		return render(request, 'events/event_details.html', context)

	context = {
		"event_details": event_details,
		"update_form": update_form,
	}
		 
	return render(request, 'events/edit_event.html', context)

# Allow the host to edit event details on the front end.
def delete_event(request, event_id):
	# Load event model details to prepopulate the form fields.
	event_to_delete = get_object_or_404(Event, pk = event_id)
	
	context = {
		"delete_event": event_to_delete,
	}

	if request.method == "POST":
		event_to_delete.delete()

		return render(request, 'events/existing_event.html')
		 
	return render(request, 'events/delete_event.html', context)


# [END GOAL] Front-End: Formatted Front-End UI heavy event creation
def end_product(request):
	return render(request, 'events/event_frontend.html')

events/templates/events/event_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="initial-scale=1, width=device-width">
        <!-- Load Google Sign-in-->
        <meta name="google-signin-scope" content="profile email">
        <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com">
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <!-- Load Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
        </script>
        <!-- Font Awesome icons (free version)-->
        <script 
        src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous">
        </script>
        <link rel="stylesheet" href="{% static 'events/styles.css' %}">
        <title>Events</title>

    </head>
    <!-- Upper Navbar links to important app sections-->
    <header>
        <div class="navbar navbar-dark box-shadow" style="background-color: hsl(218, 41%, 15%);">
          <div class="container d-flex justify-content-between">
            <!-- If user Athenticated provide link to profile page -->
            {% if user.is_authenticated %}
            <!-- Link to Adress if user is signed in -->
              <a href="{% url 'layoverconnections:profile' %}" class="navbar-brand d-flex align-items-center">
                <i class="fa-sharp fa-solid fa-circle-user" style="margin-right:10px;"></i>
                <strong>Profile</strong>
              </a>
            {% else %}
              <a href="/login"class="navbar-brand d-flex align-items-center">
                  <strong>Login</strong>    
              </a>
            {% endif %}

            <a href="{% url 'events:view_events' %}" class="navbar-brand d-flex align-items-center">
              <i class="fa-solid fa-people-group" style="margin-right:10px;"></i>
              <strong>Events</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Collapsible Navbar menu-->
              <div class="collapse" id="navbarHeader">
                <div class="container">
                  <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                      <h4 class="text-white"> Upcoming Events </h4>
                      <p class="text-muted">
                      Upcoming Events.</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                      <!-- Django tools for User Navbar Controls-->
                      {% if user.is_authenticated %}
                      <h4 class="text-white">Welcome, {{user.username}}</h4>
                      <ul class="list-unstyled">
                        <!-- Route to event Creation -->
                        <li><a href="{% url 'layoverconnections:events' %}" class="nav-link text-white">Create a New Event</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="/logout">Logout</a></li>
                      </ul>
                      {% else %}
                      <span class="text-white"> Please login to change your profile and join in the fun by creating or joining an event!</span>
                      <ul class="list-unstyled">
                        <!-- Route to event Creation -->
                        <li class="nav-item"><a class="nav-link" href="/login">Login</a></li>
                      </ul>
                      {% endif %}

                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
    </header>


    <body>
          <!-- Section: Design Block -->
          {% block content %}
          {% endblock %}
    </body>
</html>

events/templates/events/event_details.html
{% extends "events/event_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- Section: Area below upper navbar -->
<section class="background-radial-gradient" style="height: 100vh; overflow: auto;">
    <!-- Event Details Container -->
    <div class="card bg-glass" style="border-radius: 7px; box-shadow: 5px 5px 5px rgba(0, 0, 0, .7); border: 1px solid rgba(0, 0, 0, 0.507); max-width: 40rem; margin: auto;">
        <!-- Individual Event Details -->
        <ul class="list-group" style="padding: 3px;">

            <!-- Event Banner -->
            <li class="list-group-item" style="background-color: hsla(194, 39%, 27%, 0.87); min-height: 15rem; text-align: center; padding-top: 1.5rem;">
                <!-- Thumbnail-container Bounding div for work thumbnail. -->
                <div class="wrapper" style ="
                border-radius: 10px; 
                margin: auto;
                object-fit: contain;
                ">
                    <img src="{{ event_details.event_thumbnail.url }}" style="
                    border-radius: 10px;
                    max-height: 12rem;">
                </div>
                <span class="my-1 ls-tight" style="color: hsl(41, 79%, 85%); font-size: 1.6rem; font-weight: 450;">
                    {{ event_details.title}} 
                </span>
            </li>

            <!-- Show host thumbnail and link to profile. -->
            <li class="list-group-item" style="background-color: rgba(245, 239, 239, 0.74);"><strong>Host:</strong> </br> 

                <a href="{% url 'layoverconnections:public_profile' host.id %}" style="font-weight: 400; font-size: .4rem; color: black;">
                    <div style="                                                                    
                    vertical-align: top;
                    display: inline-block;
                    text-align: center;
                    width: 4rem;">
                    <img src= "{{ host.profile.image.url }}" style="height: 3.4rem; width: 3.4rem; border-radius: 50px;">
                        <span style="display: block;"><strong>{{ host.first_name }}</strong></span>
                    </div>
                </a>
            </li>

            <!-- Description-->
            <li class="list-group-item" style="background-color: rgba(245, 239, 239, 0.74);"><strong>Details:</strong> </br> 
                {{event_details.description}} </br>

            </li>
            <!-- Scheduled Time -->
            <li class="list-group-item" style="background-color: rgba(245, 239, 239, 0.74);">
                <div style = "display: flex;">
                    <div style="flex: auto;">
                        <strong>Start Time:</strong> </br> 
                        {{event_details.start_time}}
                    </div>
                    <div style="flex: auto;">
                        <strong>End Time:</strong> </br> 
                            {{event_details.end_time}}
                    </div>
                </div>
            </li>
            <!-- Page Navigation Button Controls. -->
            <li class="list-group-item" style="background-color: rgba(245, 239, 239, 0.74);">
                <div style = "display: flex;">
                    <!-- Only allow user to join if they are signed in. -->
                    {% if user.is_authenticated %}
                        <!-- Conditional filtering: Enforce check on participant permissions to allow navigation to edit controls. -->
                        {% if perms.events.can_edit_event %}
                            <!-- Evaluate whether the current user is the host with edit controls. -->
                            {% if event_details.host == request.user.id %}
                                <div style="flex: auto;">
                                    <button class="btn btn-outline-info mt-2" style="background-color:hsla(197, 16%, 83%, 0.813); border: 1px;">
                                        <strong>
                                            <!-- Generic Model access template boilerplate -->
                                            <a href="{%  url 'events:edit_event' event_details.id %}" style="color: #050505; text-decoration:none;">
                                                <i class="fa-solid fa-pen" style="color: rgb(6, 6, 6)"></i> Edit Event: 
                                            </a>
                                        </strong>
                                    </button>
                                </div>
                            {% else %}
                            <!-- If the user is not the host give them the option to join the event. -->
                            <div style="flex: auto;">
                                <form method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-info mt-2" style="background-color:hsla(197, 16%, 83%, 0.813); border: 1px;" type="submit">
                                        <strong style="color: #000000; text-decoration:none;"> Join </strong>
                                    </button>
                                </form>
                            </div>

                            {% endif %}
                        <!-- Provide Option for any other logged in user to join the event.-->
                        {% else %}
                            <div style="flex: auto;">
                                <form method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-info mt-2" style="background-color:hsla(197, 16%, 83%, 0.813); border: 1px;" type="submit">
                                        <strong style="color: #000000; text-decoration:none;"> Join </strong>
                                    </button>
                                </form>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </li>

        </ul>

    </div>
</section>

{% endblock %}

events/templates/events/event_frontend.html
{% load static %}

<!DOCTYPE html>
<!-- User Event Creation Portal -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <title> Events </title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
      </script>
    <!-- Font Awesome icons (free version)-->
      <script 
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous">
      </script>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'sandbox/styles.css' %}">
</head>

<!-- Upper Navbar linkin to important pages-->
<header>
    <div class="navbar navbar-dark box-shadow" style="background-color: hsl(218, 41%, 15%);">
        <div class="container d-flex justify-content-between">
        <!-- If user Athenticated provide link to profile page -->
        <a href="{% url 'layoverconnections:profile' %}" class="navbar-brand d-flex align-items-center">
            <i class="fa-sharp fa-solid fa-circle-user" style="margin-right:10px;"></i>
            <strong>Profile</strong>
        </a>
        <a href="{% url 'layoverconnections:homepage' %}" class="navbar-brand d-flex align-items-center">
            <i class="fa-sharp fa-solid fa-plane" style="margin-right:10px;"></i>
            <strong>Main Page</strong>
        </a>
        <a href="#" class="navbar-brand d-flex align-items-center ">
            <button type="button" class="btn btn-primary" style="background-color:hsl(202, 65%, 20%)">
            Messages <span class="badge bg-secondary">4</span>
            </button>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Collapsible Navbar menu-->
            <div class="collapse" id="navbarHeader">
            <div class="container">
                <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white"> Upcoming Events </h4>
                    <p class="text-muted">
                    Upcoming Events [Django placeholder Populate quick info of upcoming events].</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Welcome, {{user.username}}</h4>
                    <ul class="list-unstyled">
                    <!-- Django tools for User Navbar Controls-->
                    {% if user.is_authenticated %}
                    <li><a href="#" class="nav-link text-white">Check into the Airport</a></li>
                    <!-- Route to event Creation -->
                    <li><a href="{% url 'layoverconnections:events' %}" class="nav-link text-white">Create a New Event</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="/logout">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="/login">Login</a></li>
                    {% endif %}
                    </ul>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</header>

<!-- TODO work on an html create event page to visualize UI -->
<body style="background-color: rgba(187, 187, 187, 0.897)">
    <!-- Page Title-->
    <div style="text-align: center; background-color:hsl(202, 65%, 20%); color: white; padding:.5rem;">
        <h1><strong>Create Event</strong></h1>
    </div>
    <!-- Center Piece -->
    <div id="event_main" style="background-color: whitesmoke; padding: 2rem; width: 32rem;">
        <div class="card mb-4 box-shadow" style="border-radius: 10px; box-shadow: 5px 5px 5px rgba(0, 0, 0, .7); border: 2px solid rgba(0, 0, 0, 0.507);">
            <div class="card-img-overlay" style ="background: linear-gradient(0deg, #00000088 45%, #ffffff44 100%)">
              <h1 class="card-text text-white text-center" style="margin-top:100px;"><strong>Create Event</strong></h1>
            </div>
            <img src= "{% static '/images/jeshoots-com-mSESwdMZr-A-unsplash.jpg' %}" class="card-img-top" style="height:275px;" alt="Create Event">
            <div class="card-body" style="background-color: hsla(197, 45%, 58%, 0.603);">
              <!-- Event Form controls -->
              <ul class="list-group" style="opacity: 70%;">
                <li class="list-group-item">
                    <p> 
                        Hi {{ user.first_name }} Nice of you to show up. Theres plently of awesome people around you also looking to kill sometime.
                        Chicago can be a neat playground with the proper company. What kind of vibe are you feeling and what do you wanna see?
                    </p>
                </li>
                <li class="list-group-item">Upload a Picture?</li>
                <!-- TODO: Populate category of preset events added to the event model.-->
                <li class="list-group-item">
                    Category
                    <select class="form-select" aria-label="Default select example">
                        <option selected>Select...</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                </li>
                <li class="list-group-item">
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Event Details</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>
                </li>
                <li class="list-group-item">
                    <div id="date-picker-example" class="md-form md-outline input-with-post-icon datepicker" inline="true">
                        <label for="start">Select Date:</label>
                        <input type="date" class="form-control" id="start" name="trip-start"
                            value="2018-MM-DD"
                            min="2018-01-01">
                    </div>
                </li>
                <!-- Start End Time and Duration of Event -->
                <li class="list-group-item">
                    <div class="row">
                        <div class="col">
                        Start:
                          <input type="time" class="form-control" placeholder="Start Time:" label="Start">
                        </div>
                        <div class="col">
                        Finish:
                          <input type="time" class="form-control" placeholder="End Time:">
                        </div>
                    </div> 
                    <div class="row" style="padding-left: 1rem;">
                        Duration 00:00
                    </div>
                </li>
                <li class="list-group-item">Creator</li>
                <li class="list-group-item">Invite Guest? </li>
                <li class="list-group-item">Active or Finished Status</li>
             </ul>
              <div class="d-flex justify-content-between align-items-center" style="padding-top:1rem;">
                <div class="btn-group">
                  <button type="button" class="btn btn-md btn-outline-secondary text-white" style="background-color:hsl(0, 2%, 32%)"><strong>Create</strong></button>
                </div>
              </div>
            </div>
        </div>
    </div>
        <!-- Test Section for new form -->
        <div id="event_main" style="background-color: whitesmoke; padding: 2rem; width: 32rem;">
            <div class="card mb-4 box-shadow" style="border-radius: 10px; box-shadow: 5px 5px 5px rgba(0, 0, 0, .7); border: 2px solid rgba(0, 0, 0, 0.507);">
                <div class="card-img-overlay" style ="background: linear-gradient(0deg, #00000088 45%, #ffffff44 100%)">
                  <h1 class="card-text text-white text-center" style="margin-top:100px;"><strong>Create Event</strong></h1>
                </div>
                <div>
                    
                </div>
        </div>
</body>