Layover_Connections/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('layoverconnections.urls', namespace='layoverconnections')),
    path('events/', include('events.urls', namespace='events')),
    path('admin/', admin.site.urls),
]

Layover_Project/Layover_Connections_app/urls.py
# django_project/urls.py 
from django.contrib import admin
from django.urls import path, include # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signon/', include('django.contrib.auth.urls')), # new
]

events/urls.py
from django.urls import path
from django.contrib import admin
from . import views

# Pre-Deployment Media Storage recommendations
from django.conf import settings
from django.conf.urls.static import static

# Event paths: events/<view_of_interest>
app_name = "events"
urlpatterns = [
    path("", views.view_events, name="view_events"),
    path("create_event", views.create_event, name="create_event"),
    path("end_product", views.end_product, name="formatted_event"),
    path("<int:event_id>/event_details/", views.event_details, name="event_details"),
    path("<int:event_id>/edit_event/", views.edit_event, name="edit_event"),
    path("<int:event_id>/delete_event/", views.delete_event, name="delete_event"),
] 

# Pre-Deployment check to see if currently in DEBUG mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

layoverconnections/urls.py
from django.urls import path
from django.contrib import admin
from layoverconnections import views
from . import views

# Pre-Deployment Media Storage recommendations
from django.conf import settings
from django.conf.urls.static import static

app_name = "layoverconnections"

# Homepage is django placeholder consider removing it
urlpatterns = [
    path("", views.index, name="index"),
    path("main", views.homepage, name="homepage"),
    path("register", views.register_request, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("user_profile", views.user_profile, name="profile"),
    path("<int:user_profile_id>/edit_profile", views.edit_profile, name="editprofile"),
    path("<int:user_id>/user_profile/", views.public_profile, name="public_profile"),
    path("delete_profile", views.delete_profile, name="delete_profile"),
    path("about_me", views.edit_bio, name="aboutme"),
    path("events", views.create_event, name="events"),
] 

# Pre-Deployment check to see if currently in DEBUG mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

layoverconnections/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings

# Creates a User Profile with a one to one relationship with User Model
# Contains information for: profilepic, hometown, age, bio
class Profile(models.Model):
    # Create a one to one relationship with the User Model
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    userimage_1 = models.ImageField(default='placeholder.jpg', upload_to='profile_pics')
    userimage_2 = models.ImageField(default='placeholder.jpg', upload_to='profile_pics')
    userimage_3 = models.ImageField(default='placeholder.jpg', upload_to='profile_pics')
    userimage_4 = models.ImageField(default='placeholder.jpg', upload_to='profile_pics')
    hometown = models.CharField(max_length= 25, null=True)
    age = models.IntegerField(null=True)
    profile = models.CharField(max_length=500,
                                blank=True)
    bio = models.CharField(max_length=500,
                            blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        # Provide size restrictions of user uploaded images (300x300)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

events/forms.py
from django import forms
from .models import Event

# Event model forms
# Formatting for event creation.
class EventCreationForm(forms.ModelForm):
	title = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 1}))
	start_time = forms.CharField(label= 'Start Time: [ yyyy-mm-dd 00:00 ]')
	description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
	# TODO Fix the default event_thumbnail error.
	#event_thumbnail = forms.ImageField(required=False)
	event_thumbnail = forms.ImageField()

	class Meta:
		model = Event
		fields = ['title', 'event_thumbnail', 'start_time', 'end_time', 'description']


# [Placeholder form] in case I make the update form different.
class EventUpdateForm(forms.ModelForm):
	title = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 1}))
	start_time = forms.CharField(label= 'Start Time: [ yyyy-mm-dd 00:00 ]')
	description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
	event_thumbnail = forms.ImageField()

	class Meta:
		model = Event
		fields = ['title', 'event_thumbnail', 'start_time', 'end_time', 'description']

layoverconnections/forms.py
# Format Built-In Django Server-side validated forms here
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

# User Registration forms
class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2' ]

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

# User Model information Related Forms
class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()
	
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email']
		  
class ProfileUpdateForm(forms.ModelForm):
	bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 7}))
	image = forms.ImageField()

	class Meta:
		model = Profile
		fields = ['image', 'age', 'hometown', 'bio']

# Formatting for image upload forms
class ImageUploadForm(forms.ModelForm):
	image = forms.ImageField(label= 'Upload Image')

	class Meta:
		model = Profile
		fields = ['image', 'userimage_1', 'userimage_2', 'userimage_3', 'userimage_4']

events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Permission
from events.models import Event, User
from django.contrib import messages
from .forms import EventCreationForm


# Base Event Page to encapsulate all event controls.
def event_base(request):
	return render(request, 'events/event_splashpage.html')

# Base Event Page to encapsulate all event controls.
def view_events(request):
	event_list = Event.objects.all()

	context = {
		"Events": event_list,
	}

	return render(request, 'events/existing_event.html', context)

# Load form variables for the event creation portal.
@login_required 
def create_event(request):
	if request.method == 'POST':
		Event_Form = EventCreationForm(request.POST, request.FILES)
		# Store host & title, apply host controls to the current user.
		host = request.user

		if Event_Form.is_valid():
			event_title = Event_Form.cleaned_data['title']
			Event_Form.save()
			# Retrieve event and add current user as participant, store user to make them a host with permissions in edit_details().
			New_Event = Event.objects.get(title=event_title)
			New_Event.host = (host.id)
			New_Event.participants.add(host)
			# Provide Host with elevated event permissions to allow them to modify/delete the event.
			edit_permission = Permission.objects.get(codename='can_edit_event')
			print(f"This is the permission object queried {edit_permission}")
			host.user_permissions.add(edit_permission)

			New_Event.save()

			messages.success(request, f"Event has been created")
			return redirect(reverse("events:view_events"))
	else:
		Event_Form = EventCreationForm()

	context = {
		'Event_Form': Event_Form
	}

	return render(request, 'events/create_event.html', context)


# Render single event details Allow the host to edit and for guest to join.
def event_details(request, event_id):
	event_details = get_object_or_404(Event, pk = event_id)
	# Query Host Participant details to link profile and thumbnail.
	host_id = event_details.host
	host = User.objects.get(id=host_id)

	# Allow user to join event.
	if request.method == "POST":
		event_details.participants.add(request.user)
		event_details.save()
		messages.success(request, f"You have joined the event.")
		return render(request, 'events/event_details.html', {"event_details": event_details})

	context = {
		"event_details": event_details,
		"host": host,
	}

	return render(request, 'events/event_details.html', context)


# Allow Host User to modify the event. Raise HTTP 403 Error code if the user is unauthorized.
@permission_required('events.can_edit_event', raise_exception=True)
def edit_event(request, event_id):
	# Load event model details to prepopulate the form fields.
	event_details = get_object_or_404(Event, pk = event_id)
	update_form = EventCreationForm(instance=event_details)

	# Store user id to validate against event host id
	current_user = request.user
	host = current_user.id
	event_host = event_details.host

	# Only allow user to modify event details if they're a host.
	if host == event_host:
		if request.method == "POST":
			update_form = EventCreationForm(request.POST,
								   		 	request.FILES,
											instance=event_details)
			if update_form.is_valid():
				update_form.save()
				# FIXME Django routing messages to admin/ login portal url insert messages with JavaScript
				messages.success(request, f"Your Event {format(update_form)} has been updated.")
				return render(request, 'events/event_details.html', {"event_details": event_details,})
		# TODO : Add JS popup denoting that changes are invalid.
		else:
			update_form = EventCreationForm(instance=event_details)
	# Route user to event details if they aren't the host.
	# TODO Add JavaScript popup message saying user is unauthorized to edit event information
	else:
		context = {"event_details": event_details,}
		return render(request, 'events/event_details.html', context)

	context = {
		"event_details": event_details,
		"update_form": update_form,
	}
		 
	return render(request, 'events/edit_event.html', context)

# Allow the host to edit event details on the front end.
def delete_event(request, event_id):
	# Load event model details to prepopulate the form fields.
	event_to_delete = get_object_or_404(Event, pk = event_id)
	
	context = {
		"delete_event": event_to_delete,
	}

	if request.method == "POST":
		event_to_delete.delete()

		return render(request, 'events/existing_event.html')
		 
	return render(request, 'events/delete_event.html', context)


# [END GOAL] Front-End: Formatted Front-End UI heavy event creation
def end_product(request):
	return render(request, 'events/event_frontend.html')

layoverconnections/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import NewUserForm, UserUpdateForm, ProfileUpdateForm, ImageUploadForm
from django.contrib.auth.models import User
from .models import Profile


# [User Login & Registration] Views.

# Splash page routing
def index(request):
	if not request.user.is_authenticated:
		return render(request, "layoverconnections/splashpage.html")
	return render(request, 'layoverconnections/homepage.html')

# New user registration validation
def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST) 
		if form.is_valid():
			user = form.save()
			login(request, user)
			# Create Profile to add one-to-one to the newly registered User.
			new_user_profile = Profile.objects.create(user = request.user)
			new_user_profile.save()
			messages.success(request, "Registration successful.")
			return redirect("layoverconnections:login")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="layoverconnections/register.html", context={"register_form":form})

# View functionality for user log in. 
def login_view(request):
	if request.method == "POST":
		username = request.POST["username"]
		password = request.POST["password"] 
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect("layoverconnections:homepage")
		else:
			return render(request, "layoverconnections/login.html",
				messages.info(request, "Invalid Credentials.") )
	return render(request, 'layoverconnections/login.html')

# Logout Functionality
def logout_request(request):
	logout(request)
	return render(request, "layoverconnections/login.html",
		messages.info(request, "You have Succesfully logged out.") )


# [User Profile] Views
# User profile routing & CRUD Operations

# [CRUD] - Read Operations
# Route to logged_in user's profile
@login_required
def user_profile(request):
	return render(request, 'layoverconnections/user_profile.html')

# Route to a specific user's public profile via their id.
@login_required
def public_profile(request, user_id):
	queried_user = User.objects.get(id = user_id) 
	
	context = {
		"queried_user": queried_user,
	}
	return render(request, 'layoverconnections/public_profile.html', context)


# [CRUD] - Update Operations
# Update User Profile information
@login_required
def edit_profile(request, user_profile_id):
	# Query user profile based on logged in user
	current_user = request.user
	user_profile_id = current_user.id
	queried_profile = Profile.objects.get(user = current_user)

	# Validate that current user is the owner of the user profile to allow editing.
	if queried_profile.user.id == user_profile_id:
		if request.method == "POST":
			u_form = UserUpdateForm(request.POST, instance=request.user)
			p_form = ProfileUpdateForm(request.POST, 
									request.FILES, 
									instance=request.user.profile)
			if u_form.is_valid() and p_form.is_valid():
				u_form.save()
				p_form.save()

				return render(request, 'layoverconnections/user_profile.html', messages.success(request, f"Your account has been updated.") )

		else:
			u_form = UserUpdateForm(instance=request.user)
			p_form = ProfileUpdateForm(instance=request.user.profile)

		context = {
			'u_form': u_form,
			'p_form': p_form
		}
		# Update profile information and display it to the user.
		return render(request, 'layoverconnections/edit_profile.html', context)
	
	# Return user to Log-In if validation fails display message of invalid credentials.
	return render(request, "layoverconnections/login.html",
		messages.info(request, "Invalid Credentials.") )

# Update About Me Section
@login_required
def edit_bio(request):
	if request.method == "POST":
		profile_form = ProfileUpdateForm(request.POST, 
								   request.FILES, 
								   instance=request.user.profile)
		picture_form = ImageUploadForm(request.POST, 
										request.FILES, 
										instance=request.user.profile)
		if profile_form.is_valid() and picture_form.is_valid():
			profile_form.save()
			picture_form.save()
			messages.success(request, f"Your bio has been updated.") 
			return render(request, 'layoverconnections/user_profile.html')

	else:
		profile_form = ProfileUpdateForm(instance=request.user.profile)
		picture_form = ImageUploadForm(instance=request.user.profile)


	context = {
		'profile_form': profile_form,
		'picture_form': picture_form
	}

	return render(request, 'layoverconnections/about_me.html', context)

# CRUD - Delete Operations
# Allow user to delet their profile and user account
@login_required
def delete_profile(request):
	# Query user profile based on logged in user
	current_user = request.user
	profile_to_delete = Profile.objects.get(user = current_user)
	user_to_delete = User.objects.get(username = current_user.username)
	
	context = {
		"delete_profile": profile_to_delete,
	}

	if request.method == "POST":
		profile_to_delete.delete()
		user_to_delete.delete()

		return render(request, 'layoverconnections/login.html')
	
	return render(request, 'layoverconnections/delete_profile.html', context)

# Homepage Based Views

# Configure Requests for the homepage http request
def homepage(request):
	return render(request, 'layoverconnections/homepage.html')


#  path("events", views.create_event, name="events")
# Routing to a user profile.
@login_required
def create_event(request):
	return render(request, 'layoverconnections/events.html')

layoverconnections/templates/layoverconnections/about_me.html
{% extends "layoverconnections/base_profile.html" %}

{% block content %}
{% load crispy_forms_tags %}   

<section class="h-100 gradient-custom-2">
    <div class="container py-1 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card">
            <div class="rounded-top text-white d-flex flex-row" style="background-color: hsl(218, 41%, 15%); height:200px;">
              <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                <!-- Image upload from Database if none present provides a default thumbnail-->
                <img src="{{ user.profile.image.url }}"
                  alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2"
                  style="width: 150px; z-index: 1">
              </div>
              <!-- Populate User Defined information. -->
              <div class="ms-3" style="margin-top: 100px;">
                <h5>{{ user.first_name }} {{ user.last_name }}</h5>
                <p>
                        Age: {{ user.profile.age }}, 
                  <br> Hometown: {{ user.profile.hometown }}
                </p>
              </div>
            </div>

            <!-- Django forms to apply updates to user profile. -->
            <div class="py-4 text-black" style="background-color: #f8f9fa;">
              <div class="d-flex justify-content-end text-center">
                <!-- Route to the main page -->
                <div style="padding-right: 1rem;">
                  <button type="button" class="btn btn-md btn-outline-secondary" style="background-color:hsl(194, 65%, 20%);">
                    <strong><a href="{% url 'layoverconnections:profile' %}" style="color: #f8f9fa; text-decoration:none;">Return to Profile</a></strong>
                  </button>
                </div>   
            </div>

            <!-- Forms to Edit User Profile-->
            <div class="card-body pt-4 text-black">
              <div class="mb-5">
                <div  style="background-color: #f8f9fa;">
                  <!-- <form method="POST" enctype="multipart/form-data"> -->
                  <div>
                    <li class="list-group-item">
                      <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- User About Me Section -->
                        <!-- Profile Picture-->
                        <li class="list-group-item" style="background-color:hsla(194, 65%, 20%, 0.815);"> 
                          <strong style="color: #f8f9fa;"> Profile Picture </strong>
                        </li>
                            <div class="card">
                              <img class="card-img-top" src="{{ user.profile.image.url }}"
                              alt="Generic placeholder image" class="img-fluid img-thumbnail"
                              style="width: 150px; padding: 1rem; ">
                              <div class="card-body">
                                <p class="card-text">
                                  {{ picture_form.image }}</p>
                              </div>
                            </div>

                        <!-- User About Me Section -->
                        <fieldset class="form">
                          <!-- Combined About me Form and Bio Form -->
                          <p> {{ profile_form | crispy }} </p>
                        </fieldset>

                        <!-- User Profile Images -->
                        <li class="list-group-item" style="background-color: hsl(220, 39%, 23%); text-align: center;"> 
                          <strong style="color: #f8f9fa;"> Upload Pictures </strong>
                        </li>
                        <!-- Image Upload Carousel-->
                        <div id="carouselExampleControlsNoTouching" class="carousel slide" data-bs-touch="false" data-bs-interval="false">
                          <div class="carousel-inner">
                          <!-- Img 1 -->
                            <div class="carousel-item active">
                                <div class="card">
                                  <div style="background-color:hsla(194, 65%, 20%, 0.815); height: 2.75rem; text-align: center; padding-top:.5rem;"> 
                                    <strong style="color: #f8f9fa;"> Image 1 </strong>
                                  </div>
                                  <img class="card-img-top" src="{{ user.profile.userimage_1.url }}" class="img-fluid img-thumbnail" style="padding: 1rem;">
                                  <div class="card-body">
                                    <p class="card-text">{{ picture_form.userimage_1 }}</p>
                                  </div>
                                </div>
                            </div>
                            <!-- Image 2 -->
                            <div class="carousel-item">
                              <div style="background-color:hsla(194, 65%, 20%, 0.815); height: 2.5rem; text-align: center; padding-top:.5rem;"> 
                                <strong style="color: #f8f9fa;"> Image 2 </strong>
                              </div>
                              <div class="card">
                                <img class="card-img-top" src="{{ user.profile.userimage_2.url }}" class="img-fluid img-thumbnail" style="padding: 1rem;">
                                <div class="card-body">
                                  <p class="card-text">{{ picture_form.userimage_2 }}</p>
                                </div>
                              </div>
                            </div>
                            <!-- Img 3 -->
                            <div class="carousel-item">
                              <div style="background-color:hsla(194, 65%, 20%, 0.815); height: 2.5rem; text-align: center; padding-top:.5rem;"> 
                                <strong style="color: #f8f9fa;"> Image 3 </strong>
                              </div>
                              <div class="card">
                                <img class="card-img-top" src="{{ user.profile.userimage_3.url }}" class="img-fluid img-thumbnail" style="padding: 1rem;">
                                <div class="card-body">
                                  <p class="card-text">{{ picture_form.userimage_3 }}</p>
                                </div>
                              </div>
                            </div>
                            <!-- Img 4 -->
                            <div class="carousel-item">
                              <div style="background-color:hsla(194, 65%, 20%, 0.815); height: 2.5rem; text-align: center; padding-top:.5rem;"> 
                                <strong style="color: #f8f9fa;"> Image 4 </strong>
                              </div>
                              <div class="card" style="margin-bottom: 1rem;">
                                <img class="card-img-top" src="{{ user.profile.userimage_4.url }}" class="img-fluid img-thumbnail" style="padding: 1rem;">
                                <div class="card-body">
                                  <p class="card-text">{{ picture_form.userimage_4 }}</p>
                                </div>
                              </div>
                            </div>
                          </div>
                          <!-- Carousel Control Buttons-->
                          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                          </button>
                          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                          </button>
                        </div>
                        <!-- Submit Profile information -->                        
                        <div class="form-group" style="margin-bottom: 7px;" method="POST" enctype="multipart/form-data">
                          <button class="btn btn-outline-info" style="background-color:hsl(194, 65%, 20%)" type="submit">
                            <strong style="color: #f8f9fa; text-decoration:none;">Update</strong>
                          </button>
                        </div>
                      </form>
                  
                  <!-- 

                    Image Upload Default HTML
                        <li class="list-group-item"><strong>profile picture</strong> <br>

                          Currently: <a href="/media/profile_pics/albert-dera-ILip77SbmOE-unsplash_8tAmmuo.jpg">profile_pics/albert-dera-ILip77SbmOE-unsplash_8tAmmuo.jpg</a><br>
                          Change: <input type="file" name="image" accept="image/*" id="id_image">

                        </li>
                  -->

                  </div>
                </div>
              </div>



            </div>
          </div>
        </div>
      </div>
    </div>

</section>
{% endblock %}

layoverconnections/templates/layoverconnections/edit_profile.html
{% extends "layoverconnections/base_profile.html" %}

{% block content %}
{% load crispy_forms_tags %}   

<section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card">
            <div class="rounded-top text-white d-flex flex-row" style="background-color: hsl(218, 41%, 15%); height:200px;">
              <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                <!-- Image upload from Database if none present provides a default thumbnail-->
                <img src="{{ user.profile.image.url }}"
                  alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2"
                  style="width: 150px; z-index: 1">
              </div>
              <!-- Populate User Defined information. -->
              <div class="ms-3" style="margin-top: 100px;">

                <h5>{{ user.first_name }} {{ user.last_name }}</h5>
                <p>
                        Age: {{ user.profile.age }}, 
                  <br> Hometown: {{ user.profile.hometown }}
                </p>
              </div>
            </div>
            <!-- Django forms to apply updates to user profile. -->
            <div class="p-4 text-black" style="background-color: #f8f9fa;">
                <!-- Routing options -->
                <div class="container" style="padding-top: 1rem; display: flex; justify-content: space-between;">
                  <!-- Route to the main page -->
                  <button class="btn btn-outline-info mb-1" style="background-color:hsl(194, 65%, 20%); border: 1px;">
                    <strong><a href="{% url 'layoverconnections:profile' %}" style="color: #f8f9fa; text-decoration:none;">Return to Profile</a></strong>
                  </button>

                  <!-- Delete Profile controls -->
                  <button class="btn btn-outline-info mb-1" style="background-color:hsl(0, 65%, 19%); border: 1px;">
                    <strong><a href="{%  url 'layoverconnections:delete_profile' %}" style="color: #f8f9fa; text-decoration:none;"> Delete Your Profile? </a></strong>
                  </button>
                </div>

            <!-- Forms to Edit User Profile-->
            <div class="card-body p-3 text-black">                </div>
              <div class="mb-5">
                <div class="py-4" style="background-color: #f8f9fa;">
                  <!--  User Profile information -->
                  <div>
                    <form method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      <fieldset class="form-group">
                        <!-- Individual Form Fields -->
                        <ul class="list-group" style="padding-5px;">
                          <!-- User Login information -->
                          <li class="list-group-item" style="background-color:hsla(194, 65%, 20%, 0.815);"> 
                            <strong style="color: #f8f9fa;"> Login Information </strong> 
                          </li>
                          <li class="list-group-item"><strong>First Name</strong> </br> {{ u_form.first_name }}</li>
                          <li class="list-group-item"><strong>Last Name</strong> </br> {{ u_form.last_name }}</li>
                          <li class="list-group-item"><strong>Username</strong> </br> {{ u_form.username }}</li>
                          <li class="list-group-item"><strong>Email</strong> </br> {{ u_form.email }}</li>
                          <!-- User profile information -->
                          <li class="list-group-item" style="background-color:hsla(194, 65%, 20%, 0.815);"> 
                            <strong style="color: #f8f9fa;"> Profile Information </strong> 
                          </li>
                          <li class="list-group-item"><strong>Age</strong> </br> {{ p_form.age }}</li>
                          <li class="list-group-item"><strong>Hometown</strong> </br> {{ p_form.hometown }}</li>
                          <li class="list-group-item"><strong>Profile Picture</strong> </br> {{ p_form.image }}</li>
                          <li class="list-group-item"><strong>About Me</strong> </br> {{ p_form.bio }}</li>
                        </ul>
                      </fieldset>
                      <!-- Submit Button-->
                      <div class="form-group">
                        <button class="btn btn-outline-info mt-3" style="background-color:hsl(194, 65%, 20%)" type="submit">
                          <strong style="color: #f8f9fa; text-decoration:none;">Update</strong>
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}